<?php

namespace ValtonsBundle\Repository;

/**
 * CartaporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartaporteRepository extends \Doctrine\ORM\EntityRepository
{
}
